// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Data;

namespace StarWars.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("StarWars.Models.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StarWars.Models.Episode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("StarWars.Models.Character", b =>
                {
                    b.HasOne("StarWars.Models.Character", null)
                        .WithMany("Friends")
                        .HasForeignKey("CharacterID");
                });

            modelBuilder.Entity("StarWars.Models.Episode", b =>
                {
                    b.HasOne("StarWars.Models.Character", null)
                        .WithMany("Episodes")
                        .HasForeignKey("CharacterID");
                });

            modelBuilder.Entity("StarWars.Models.Character", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
